### ISSUE TITLE
스켈레톤 프로젝트 초기 설정

### ISSUE THREAD

**Issue by Zamoca42** [pre-onboarding-backend-G/team-g-project-skeleton#1]
- [x] 각종 템플릿들
	- [x] .gitmessage (커밋 템플릿)
	- [x] 이슈/버그/PR 템플릿 - 이슈는 혹시 몰라서 추가
- [x] common 레이어
    - [x] [Global scoped Pipes](https://docs.nestjs.com/pipes#global-scoped-pipes)
    - [x] [Global Exception Filter](https://docs.nestjs.com/exception-filters)
    - [x] swagger([@nestjs/swagger](https://docs.nestjs.com/openapi/introduction))
    - [x] CORS 미들웨어(https://docs.nestjs.com/security/cors)
    - [x] 환경변수 컨트롤([@nest/config](https://docs.nestjs.com/techniques/configuration#installation))
- [x] CI 설정
- [x] #3
- [ ] 기본 인증 모듈
- [x] #4
- [x] 도커

초기설정에서 필요한 사항에 대해 코멘트 부탁드립니다!

**Comment by myeongseoklee** [comment]
생각해본 부분은 아래와 같습니다. 어떻게 생각하시나요??!

1. morgan 미들웨어 추가
2. cors 미들웨어 추가
3. env별로 config 설정(@nest/config)하거나 logging(winston)을 따로 처리할 지 논의해봐야 할 것 같아요.

**Comment by Zamoca42** [comment]
> 생각해본 부분은 아래와 같습니다. 어떻게 생각하시나요??!
> 
> 1. morgan 미들웨어 추가
> 2. cors 미들웨어 추가
> 3. env별로 config 설정(@nest/config)하거나 logging(winston)을 따로 처리할 지 논의해봐야 할 것 같아요.

morgan과 winston은 어떤 차이가 있나요? 둘 다 로깅 라이브러리가 맞나요?
우선은 global exception filters에서 logger로 간단하게 로깅 처리를 하고 로깅을 따로 처리할지 논의해보는게 좋을거 같습니다.

env도 `@nest/config`를 사용하는게 좋다고 저는 생각하는데 다른분들 의견은 어떤지 궁금하네요.
다른 방법으로는 dotenv 라이브러리를 사용하는게 있을거같습니다.

저도 cors는 미들웨어에서 설정해주는게 간편해서 선호하고있습니다

**Comment by myeongseoklee** [comment]
> > 생각해본 부분은 아래와 같습니다. 어떻게 생각하시나요??!
> > 
> > 1. morgan 미들웨어 추가
> > 2. cors 미들웨어 추가
> > 3. env별로 config 설정(@nest/config)하거나 logging(winston)을 따로 처리할 지 논의해봐야 할 것 같아요.
> 
> morgan과 winston은 어떤 차이가 있나요? 둘 다 로깅 라이브러리가 맞나요? 우선은 global exception filters에서 logger로 간단하게 로깅 처리를 하고 로깅을 따로 처리할지 논의해보는게 좋을거 같습니다.
> 
> env도 `@nest/config`를 사용하는게 좋다고 저는 생각하는데 다른분들 의견은 어떤지 궁금하네요. 다른 방법으로는 dotenv 라이브러리를 사용하는게 있을거같습니다.
> 
> 저도 cors는 미들웨어에서 설정해주는게 간편해서 선호하고있습니다

morgan은 http req/res 관련 로깅에 사용했었고
winston은 내부 코드 동작 로깅에 사용했었습니다!

**Comment by myeongseoklee** [comment]
README 템플릿도 추가해두면 어떨까요~?

다음과 같은 내용을 포함하면 좋다고 합니다.

- 간단한 소개 1~2줄(메인 페이지 이미지 1장)
- 아키텍처(이미지 1장): 어떤 식으로 배포가 되어있는지
- 주요 라이브러리 소개 5개
- 프로젝트 배포링크
- REST API 문서 링크
- 주요 기능 소개(이미지는 최소화, 읽을 때 피로감을 준다. 복잡한 기능을 소개 한다면, 최대 3개까지만 넣기)
- 개발 주요 로드맵(체크리스트)
    - 개발해온 내역
    - 프로젝트를 쭉 이어나가고 있다면 앞으로 어떤 개발이 남아있는지를 작성
- Author
- License
- FAQ
- Contribute: 코드 기여를 받을거라면 하는 방법, 어떻게 받을지 안내
- Contact

ex) https://github.com/othneildrew/Best-README-Template/blob/master/README.md

**Comment by Zamoca42** [comment]
@myeongseoklee 오 README에 뭘 적을지 고민중이였는데 의견 감사합니다! 추가해보겠습니다.

프로젝트 배포링크는 어떤걸까요?

**Comment by myeongseoklee** [comment]
> @myeongseoklee 오 README에 뭘 적을지 고민중이였는데 의견 감사합니다! 추가해보겠습니다.
> 
> 프로젝트 배포링크는 어떤걸까요?

앞단 화면을 구현해서 배포한 경우에 넣는 링크입니다. 저희는 앞단 구현이 있을지 없을지 모르니 빼도 될 것 같아요.
